# .streamlit/secrets.toml

[connections.supabase]
SUPABASE_URL = "https://orpaeteaseulhjpvlbnr.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ycGFldGVhc2V1bGhqcHZsYm5yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDQyNTM1OTAsImV4cCI6MjAxOTgyOTU5MH0.pzaNnujkF0Ddw5mpDh8JKcgE6FKHWqBnlsSHGH_wz98"
